-- AlterTable
ALTER TABLE "User" ADD COLUMN     "role_id" TEXT NOT NULL DEFAULT 'clv1j8y6m000008l2h000002';

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "Role"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
